/*

 SRC/CONTROLPANEL.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define controlPanelBank 0

/* Super Gameboy palette 0 */
#define controlPanelSGBPal0c0 6076
#define controlPanelSGBPal0c1 8935
#define controlPanelSGBPal0c2 6596
#define controlPanelSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define controlPanelSGBPal1c0 6076
#define controlPanelSGBPal1c1 8935
#define controlPanelSGBPal1c2 6596
#define controlPanelSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define controlPanelSGBPal2c0 6076
#define controlPanelSGBPal2c1 8935
#define controlPanelSGBPal2c2 6596
#define controlPanelSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define controlPanelSGBPal3c0 6076
#define controlPanelSGBPal3c1 8935
#define controlPanelSGBPal3c2 6596
#define controlPanelSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define controlPanelCGBPal0c0 6076
#define controlPanelCGBPal0c1 8935
#define controlPanelCGBPal0c2 6596
#define controlPanelCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define controlPanelCGBPal1c0 6076
#define controlPanelCGBPal1c1 8935
#define controlPanelCGBPal1c2 6596
#define controlPanelCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define controlPanelCGBPal2c0 6076
#define controlPanelCGBPal2c1 8935
#define controlPanelCGBPal2c2 6596
#define controlPanelCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define controlPanelCGBPal3c0 6076
#define controlPanelCGBPal3c1 8935
#define controlPanelCGBPal3c2 6144
#define controlPanelCGBPal3c3 9983

/* Gameboy Color palette 4 */
#define controlPanelCGBPal4c0 6076
#define controlPanelCGBPal4c1 8935
#define controlPanelCGBPal4c2 6596
#define controlPanelCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define controlPanelCGBPal5c0 6076
#define controlPanelCGBPal5c1 8935
#define controlPanelCGBPal5c2 6596
#define controlPanelCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define controlPanelCGBPal6c0 6076
#define controlPanelCGBPal6c1 8935
#define controlPanelCGBPal6c2 6596
#define controlPanelCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define controlPanelCGBPal7c0 6076
#define controlPanelCGBPal7c1 8935
#define controlPanelCGBPal7c2 6596
#define controlPanelCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char controlPanelCGB[];
/* Start of tile array. */
extern unsigned char controlPanel[];

/* End of SRC/CONTROLPANEL.H */
