/*

 DOOR.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 3

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define doorBank 0

/* Super Gameboy palette 0 */
#define doorSGBPal0c0 6076
#define doorSGBPal0c1 8935
#define doorSGBPal0c2 6596
#define doorSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define doorSGBPal1c0 6076
#define doorSGBPal1c1 8935
#define doorSGBPal1c2 6596
#define doorSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define doorSGBPal2c0 6076
#define doorSGBPal2c1 8935
#define doorSGBPal2c2 6596
#define doorSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define doorSGBPal3c0 6076
#define doorSGBPal3c1 8935
#define doorSGBPal3c2 6596
#define doorSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define doorCGBPal0c0 6076
#define doorCGBPal0c1 8935
#define doorCGBPal0c2 6596
#define doorCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define doorCGBPal1c0 28539
#define doorCGBPal1c1 19026
#define doorCGBPal1c2 9513
#define doorCGBPal1c3 0

/* Gameboy Color palette 2 */
#define doorCGBPal2c0 28539
#define doorCGBPal2c1 19026
#define doorCGBPal2c2 9513
#define doorCGBPal2c3 0

/* Gameboy Color palette 3 */
#define doorCGBPal3c0 6076
#define doorCGBPal3c1 8935
#define doorCGBPal3c2 6596
#define doorCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define doorCGBPal4c0 6076
#define doorCGBPal4c1 8935
#define doorCGBPal4c2 6596
#define doorCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define doorCGBPal5c0 6076
#define doorCGBPal5c1 8935
#define doorCGBPal5c2 6596
#define doorCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define doorCGBPal6c0 6076
#define doorCGBPal6c1 8935
#define doorCGBPal6c2 6596
#define doorCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define doorCGBPal7c0 6076
#define doorCGBPal7c1 8935
#define doorCGBPal7c2 6596
#define doorCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char doorCGB[];
/* Start of tile array. */
extern unsigned char door[];

/* End of DOOR.H */
