/*

 LASER1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapLaser1Width 40
#define mapLaser1Height 18
#define mapLaser1Bank 0

extern unsigned char mapLaser1[];

/* End of LASER1.H */
