/*

 SRC/LASER.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 39

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define laserSpriteBank 0

/* Super Gameboy palette 0 */
#define laserSpriteSGBPal0c0 6076
#define laserSpriteSGBPal0c1 8935
#define laserSpriteSGBPal0c2 6596
#define laserSpriteSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define laserSpriteSGBPal1c0 6076
#define laserSpriteSGBPal1c1 8935
#define laserSpriteSGBPal1c2 6596
#define laserSpriteSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define laserSpriteSGBPal2c0 6076
#define laserSpriteSGBPal2c1 8935
#define laserSpriteSGBPal2c2 6596
#define laserSpriteSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define laserSpriteSGBPal3c0 6076
#define laserSpriteSGBPal3c1 8935
#define laserSpriteSGBPal3c2 6596
#define laserSpriteSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define laserSpriteCGBPal0c0 6076
#define laserSpriteCGBPal0c1 8935
#define laserSpriteCGBPal0c2 6596
#define laserSpriteCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define laserSpriteCGBPal1c0 6076
#define laserSpriteCGBPal1c1 8935
#define laserSpriteCGBPal1c2 6596
#define laserSpriteCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define laserSpriteCGBPal2c0 6076
#define laserSpriteCGBPal2c1 8935
#define laserSpriteCGBPal2c2 6596
#define laserSpriteCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define laserSpriteCGBPal3c0 6076
#define laserSpriteCGBPal3c1 8935
#define laserSpriteCGBPal3c2 6596
#define laserSpriteCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define laserSpriteCGBPal4c0 6076
#define laserSpriteCGBPal4c1 26265
#define laserSpriteCGBPal4c2 26260
#define laserSpriteCGBPal4c3 15871

/* Gameboy Color palette 5 */
#define laserSpriteCGBPal5c0 6076
#define laserSpriteCGBPal5c1 26422
#define laserSpriteCGBPal5c2 26260
#define laserSpriteCGBPal5c3 16352

/* Gameboy Color palette 6 */
#define laserSpriteCGBPal6c0 6076
#define laserSpriteCGBPal6c1 29396
#define laserSpriteCGBPal6c2 26260
#define laserSpriteCGBPal6c3 32224

/* Gameboy Color palette 7 */
#define laserSpriteCGBPal7c0 6076
#define laserSpriteCGBPal7c1 26425
#define laserSpriteCGBPal7c2 26260
#define laserSpriteCGBPal7c3 31775
/* CGBpalette entries. */
extern unsigned char laserSpriteCGB[];
/* Start of tile array. */
extern unsigned char laserSprite[];

/* End of SRC/LASER.H */
