/*

 LEVELSELECT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapLevelSelectWidth 40
#define mapLevelSelectHeight 18
#define mapLevelSelectBank 0

#define mapLevelSelect mapLevelSelectPLN0
extern unsigned char mapLevelSelectPLN0[];
extern unsigned char mapLevelSelectPLN1[];

/* End of LEVELSELECT.H */
