/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapWidth 40
#define mapHeight 18
#define mapBank 0

#define map mapPLN0
extern unsigned char mapPLN0[];
extern unsigned char mapPLN1[];

/* End of MAP.H */
