#ifndef ZGBMAIN_H
#define ZGBMAIN_H

#define STATES \
_STATE(STATE_GAME)\
_STATE(STATE_MENU)\
_STATE(STATE_GAME_LASER)\
STATE_DEF_END

#define SPRITES \
_SPRITE_COLOR(SPRITE_PLAYER, player, 3, FRAME_16x16, 3)\
_SPRITE_COLOR(SPRITE_DOOR, door, 3, FRAME_16x16, 4)\
_SPRITE_COLOR(SPRITE_LASER, laserSprite, 3, FRAME_16x16, 40)\
_SPRITE_COLOR(SPRITE_CONTROLLER, controlPanel, 3, FRAME_16x16, 1)\
SPRITE_DEF_END

#include "ZGBMain_Init.h"

#endif